version: '3'

services:
  mbc-prod-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mbc-prod-app
    restart: always
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - mbc-prod-network

  mbc-prod-webserver:
    build:
      context: ./nginx-prod
      dockerfile: Dockerfile
    container_name: mbc-prod-webserver
    restart: always
    volumes:
      - ./public:/var/www/html/public
      - ./devlogdna:/var/log/nginx
    ports:
      - "8084:80"
    depends_on:
      - mbc-prod-app
    networks: 
      - mbc-prod-network

networks:
  mbc-prod-network:
    driver: bridge
